public class AccountTriggerHandler extends TriggerHandler {
	
	public override void handleBeforeInsert() {
		//Execute our before insert logic
	}
	public override void handleAfterInsert() {
		//Execute out after insert logic
	}
	public override void handleBeforeUpdate() {
		//Execute our before insert logic
	}
	public override void handleAfterUpdate() {
		//Execute out after insert logic
	}
	public override void handleBeforeDelete() {
		//Execute our before insert logic
	}
	public override void handleAfterDelete() {
		//Execute out after insert logic
	}
	public override void handleAfterUndelete() {
		//Execute out after insert logic
	}
    
}